name: study
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - ampl-asl=1.0.0=h286801f_2
  - anyio=4.11.0=pyhcf101f3_0
  - aom=3.9.1=h7bae524_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py312h163523d_0
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.3.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.13.5=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - brotli=1.1.0=h6caf38d_4
  - brotli-bin=1.1.0=h6caf38d_4
  - brotli-python=1.1.0=py312h6b01ec3_4
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h6a3b0d2_0
  - ceres-solver=2.2.0=cpuhcbe332a_7
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py312hb65edc0_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - cminpack=1.3.11=hb3f8f53_0
  - coin-or-bonmin=1.8.9=h036f7c3_15
  - coin-or-cbc=2.10.12=h0c75da4_4
  - coin-or-cgl=0.60.9=h24d7dbf_6
  - coin-or-clp=1.17.10=ha5fe85a_3
  - coin-or-osi=0.108.11=h95bd113_7
  - coin-or-utils=2.11.12=hedb6bc8_6
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py312ha0dd364_2
  - cpython=3.12.11=py312hd8ed1ab_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=hb547adb_0
  - dbus=1.16.2=hda038a8_0
  - debugpy=1.8.17=py312h56d30c9_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.4.0=pyhd8ed1ab_0
  - dlib-cpp=20.0=hb19e799_0
  - eigen=3.4.0=h49c215f_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - ffmpeg=7.1.1=gpl_h93d53e2_110
  - filelock=3.19.1=pyhd8ed1ab_0
  - fltk=1.3.10=h46aaf7c_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.0=py312h5748b74_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freeimage=3.18.0=h70173bb_23
  - freetype=2.14.1=hce30654_0
  - fribidi=1.0.16=hc919400_0
  - fsspec=2025.9.0=pyhd8ed1ab_0
  - gdk-pixbuf=2.44.2=h7542897_0
  - gflags=2.2.2=hf9b8971_1005
  - giflib=5.2.2=h93a5062_0
  - glog=0.7.1=heb240a5_0
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.2.1=py312h711ec26_1
  - graphite2=1.3.14=hec049ff_2
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=11.5.1=haf38c7b_0
  - hdf5=1.14.6=nompi_he65715a_103
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.10=pyhd8ed1ab_1
  - imath=3.2.1=hf787086_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - iniconfig=2.0.0=pyhd8ed1ab_1
  - ipopt=3.14.19=hd6b6db2_1
  - ipykernel=6.30.1=pyh92f572d_0
  - ipython=9.5.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jasper=4.2.8=hc0e5025_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py312h81bd7bf_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.8=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jxrlib=1.1=h93a5062_3
  - kaldi=5.5.1172=cpu_h0f61937_1
  - kiwisolver=1.4.9=py312hdc12c9d_1
  - krb5=1.21.3=h237132a_0
  - lame=3.100=h1a8c8d9_1003
  - lark=1.3.0=pyhd8ed1ab_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libaec=1.1.4=h51d1e36_0
  - libamd=3.3.3=h5087772_7100102
  - libass=0.17.4=hcbd7ca7_0
  - libavif16=1.3.0=hb06b76e_2
  - libblas=3.9.0=36_h51639a9_openblas
  - libboost=1.88.0=h18cd856_5
  - libbrotlicommon=1.1.0=h6caf38d_4
  - libbrotlidec=1.1.0=h6caf38d_4
  - libbrotlienc=1.1.0=h6caf38d_4
  - libbtf=2.3.2=h99b4a89_7100102
  - libcamd=3.3.3=h99b4a89_7100102
  - libcblas=3.9.0=36_hb0561ab_openblas
  - libccolamd=3.3.4=h99b4a89_7100102
  - libcholmod=5.3.1=hbba04d7_7100102
  - libcolamd=3.3.4=h99b4a89_7100102
  - libcuba=4.2.2=h99b78c6_0
  - libcurl=8.14.1=h73640d1_0
  - libcxsparse=4.4.1=h9e79f82_7100102
  - libcxx=21.1.2=hf598326_0
  - libde265=1.0.15=h2ffa867_0
  - libdeflate=1.24=h5773f1b_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.6=h1da3d7d_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgfortran=15.1.0=hfdf1602_1
  - libgfortran5=15.1.0=hb74de2c_1
  - libglib=2.86.0=h1bb475b_0
  - libheif=1.19.7=gpl_h79e6334_100
  - libhwloc=2.12.1=default_h88f92a7_1000
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.0=h5505292_0
  - libklu=2.3.5=h4370aa4_7100102
  - liblapack=3.9.0=36_hd9741b5_openblas
  - liblapacke=3.9.0=36_h1b118fd_openblas
  - libldl=3.3.2=h99b4a89_7100102
  - liblzma=5.8.1=h39f12f2_2
  - libnghttp2=1.67.0=hc438710_0
  - libogg=1.3.5=h48c0fde_1
  - libopenblas=0.3.30=openmp_h60d53f8_2
  - libopenvino=2025.2.0=h56e7ac4_1
  - libopenvino-arm-cpu-plugin=2025.2.0=h56e7ac4_1
  - libopenvino-auto-batch-plugin=2025.2.0=he81eb65_1
  - libopenvino-auto-plugin=2025.2.0=he81eb65_1
  - libopenvino-hetero-plugin=2025.2.0=h273c05f_1
  - libopenvino-ir-frontend=2025.2.0=h273c05f_1
  - libopenvino-onnx-frontend=2025.2.0=h6386500_1
  - libopenvino-paddle-frontend=2025.2.0=h6386500_1
  - libopenvino-pytorch-frontend=2025.2.0=hec049ff_1
  - libopenvino-tensorflow-frontend=2025.2.0=hee62d61_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hec049ff_1
  - libopus=1.5.2=h48c0fde_0
  - libparu=1.0.0=h317a14d_7100102
  - libpng=1.6.50=h280e0eb_1
  - libprotobuf=6.31.1=h702a38d_1
  - libraw=0.21.4=h62a31ad_0
  - librbio=4.3.4=h99b4a89_7100102
  - librsvg=2.58.4=h266df6f_3
  - libscotch=7.0.10=int64_hea4d59e_0
  - libsodium=1.0.20=h99b78c6_0
  - libspex=3.2.3=h15d103f_7100102
  - libspqr=4.3.4=h775d698_7100102
  - libsqlite=3.50.4=h4237e3c_0
  - libssh2=1.11.1=h1590b86_0
  - libsuitesparseconfig=7.10.1=h4a8fc20_7100102
  - libtiff=4.7.1=h7dc4979_0
  - libtorch=2.7.1=cpu_generic_h1a72534_4
  - libumfpack=6.3.5=h7c2c975_7100102
  - libusb=1.0.29=hbc156a2_0
  - libuv=1.51.0=h6caf38d_1
  - libvorbis=1.3.7=h81086ad_2
  - libvpx=1.14.1=h7bae524_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.13.8=h4a9ca0c_1
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.0=hbb9b287_0
  - markupsafe=3.0.2=py312h998013c_1
  - matplotlib=3.10.6=py312h1f38498_1
  - matplotlib-base=3.10.6=py312h605b88b_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - metis=5.1.0=h15f6cfe_1007
  - mistune=3.1.4=pyhcf101f3_0
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - mumps-include=5.8.1=h2ca763e_4
  - mumps-seq=5.8.1=he6ca4b8_4
  - munkres=1.1.4=pyhd8ed1ab_1
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.5=pyhe01879c_0
  - nlopt=2.10.0=py312hfbc4060_1
  - nomkl=1.0=h5ca1d4c_0
  - notebook=7.4.5=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numpy=2.3.3=py312h85ea64e_0
  - occt=7.8.1=novtk_hbec2736_103
  - openexr=3.3.5=hc05139d_1
  - openfst=1.8.4=ha393de7_1
  - openh264=2.6.0=hb5b2745_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.5.4=h5503f6c_0
  - openturns=1.25=py312hfd1fc20_3
  - optree=0.17.0=py312ha0dd364_1
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pagmo=2.19.1=h3bd207c_7
  - pandas=2.3.2=py312h98f7732_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.56.4=h875632e_0
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.46=h7125dd6_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py312h2525f64_3
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h81086ad_1
  - platformdirs=4.4.0=pyhcf101f3_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - primesieve=12.8=h286801f_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.0=py312h4409184_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pugixml=1.15=hd3d436d_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyobjc-core=11.1=py312h4c66426_1
  - pyobjc-framework-cocoa=11.1=py312h3964663_1
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=8.4.2=pyhd8ed1ab_0
  - python=3.12.11=hc22306f_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.12.11=hd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytorch=2.7.1=cpu_generic_py312_hd1f36bd_4
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py312h998013c_2
  - pyzmq=27.1.0=py312hd65ceae_0
  - qhull=2020.2=h420ef59_5
  - rapidjson=1.1.0.post20240409=ha1acc90_2
  - rav1e=0.7.1=h0716509_3
  - readline=8.2=h1d1bf99_2
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.27.1=py312h6f58b40_1
  - scikit-learn=1.7.2=py312h79e0ffc_0
  - scipy=1.16.2=py312ha6bbf71_0
  - sdl2=2.32.56=h248ca61_0
  - sdl3=3.2.22=he22eeb8_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.3=pyh31c8845_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=hb028509_0
  - snappy=1.2.2=hd121638_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py312hcde60ef_0
  - suitesparse=7.10.1=h3071b36_7100102
  - svt-av1=3.1.2=h12ba402_0
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2022.2.0=h5b2e6d4_1
  - tbb-devel=2022.2.0=h89693d0_1
  - terminado=0.18.1=pyh31c8845_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h892fb3f_2
  - tomli=2.2.1=pyhe01879c_2
  - torchaudio=2.8.0=cpu_py312h72ca196_0
  - torchcodec=0.7.0=cpu_py312_hea95fb2_0
  - torchvision=0.23.0=cpu_py312_h5b694ef_0
  - torchvision-extra-decoders=0.0.2=py312hc6f43ad_3
  - tornado=6.5.2=py312h163523d_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20250822=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py312h163523d_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xorg-libice=1.1.2=h5505292_0
  - xorg-libsm=1.2.6=h5505292_0
  - xorg-libx11=1.8.12=h6a5fb8c_0
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xorg-libxext=1.3.6=hd74edd7_0
  - xorg-libxfixes=6.0.2=hc919400_0
  - xorg-libxrender=0.9.12=h5505292_0
  - yaml=0.2.5=h925e9cb_3
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h8359307_2
  - zstandard=0.25.0=py312h37e1c23_0
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - absl-py==2.3.1
      - aiofiles==24.1.0
      - chex==0.1.91
      - equinox==0.13.1
      - etils==1.13.0
      - flax==0.12.0
      - gekko==1.3.0
      - gmsh==4.14.1
      - humanize==4.13.0
      - importlib-resources==6.5.2
      - jax==0.7.2
      - jaxlib==0.7.2
      - jaxtyping==0.3.2
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.5.3
      - msgpack==1.1.1
      - opt-einsum==3.4.0
      - optax==0.2.6
      - orbax-checkpoint==0.11.25
      - protobuf==6.32.1
      - rich==14.1.0
      - simplejson==3.20.1
      - tensorstore==0.1.77
      - toolz==1.0.0
      - treescope==0.1.10
      - wadler-lindig==0.1.7
prefix: /Users/lyyric/miniconda3/envs/study
